#!/usr/bin/env python3
"""Generate src/StandardItems.lua, every item a standard set's rule can match.

The client cannot list items by class, so a standard set can only see what is in
your bags. This bundles the full list from the game's own tables on wago.tools,
with each item's expansion, so the settings can show all of it. Run it again
after a patch adds reagents.

Usage (from the addon root):
    python tools/generate_standard_items.py
"""

import csv
import io
import urllib.request
from collections import defaultdict
from pathlib import Path

OUTPUT = Path(__file__).resolve().parent.parent / "src" / "StandardItems.lua"

TRADEGOODS, OTHER_SUBCLASS = 7, 11
HOUSING, HOUSING_DYE = 20, 1


def table(name):
    # wago.tools turns away Python's default user agent.
    request = urllib.request.Request(f"https://wago.tools/db2/{name}/csv", headers={"User-Agent": "curl/8"})
    with urllib.request.urlopen(request) as response:
        return csv.DictReader(io.StringIO(response.read().decode("utf-8")))


def lua_map(items, indent):
    pad = " " * indent
    pairs = [f"[{item_id}]={expansion}," for item_id, expansion in sorted(items.items())]
    lines = [pad + " ".join(pairs[i:i + 8]) for i in range(0, len(pairs), 8)]
    return "{\n" + "\n".join(lines) + "\n" + " " * (indent - 4) + "}"


def main():
    classes = {}
    for row in table("Item"):
        classes[int(row["ID"])] = (int(row["ClassID"]), int(row["SubclassID"]))

    tradegoods, lumber, housing_dye = defaultdict(dict), {}, {}
    for row in table("ItemSparse"):
        item_id = int(row["ID"])
        class_id, subclass_id = classes.get(item_id, (None, None))
        expansion, name = int(row["ExpansionID"]), row["Display_lang"]
        if not name:
            continue
        if class_id == TRADEGOODS:
            tradegoods[subclass_id][item_id] = expansion
            if subclass_id == OTHER_SUBCLASS and "lumber" in name.lower():
                lumber[item_id] = expansion
        elif (class_id, subclass_id) == (HOUSING, HOUSING_DYE):
            housing_dye[item_id] = expansion

    subclasses = ",\n".join(
        f"        [{subclass_id}] = {lua_map(items, 12)}" for subclass_id, items in sorted(tradegoods.items())
    )
    OUTPUT.write_text(
        "-- Generated by tools/generate_standard_items.py. Do not edit by hand.\n"
        "-- itemID -> expansionID, as the game's item tables list them.\n"
        "WarbandStorage = WarbandStorage or {}\n"
        "WarbandStorage.StandardItems = {\n"
        f"    tradegoods = {{\n{subclasses},\n    }},\n"
        f"    lumber = {lua_map(lumber, 8)},\n"
        f"    housingDye = {lua_map(housing_dye, 8)},\n"
        "}\n",
        encoding="utf-8",
        newline="\n",
    )


if __name__ == "__main__":
    main()
