-- Warband Stockist: User-facing strings.
-- Centralised here so wording can be tweaked without hunting through feature
-- files. Format strings use Lua's standard %s / %d placeholders; pass through
-- string.format at the call site. Debug output stays inline with the code that
-- emits it, being diagnostics rather than copy.

WarbandStorage = WarbandStorage or {}

WarbandStorage.Strings = LuckyStrings.New("WarbandStorage.Strings", {
    addon = {
        title         = "Lucky's Warband Stockist",
        prefix        = "|cff7fd5ff[Warband Stockist]|r",
        errorPrefix   = "|cffff0000Error:|r",
        successPrefix = "|cff00ff00Success:|r",
    },

    minimap = {
        tooltipTitle = "|cffffd100Warband Stockist|r",
        click        = "Click: Open settings",
        middleClick  = "Middle-click: Toggle dev mode",
        drag         = "Drag: Move button",
        lowStock     = "%d |4item:items; low on stock",
        devMode      = "Dev mode %s.",
        devModeOn    = "|cff00ff00enabled|r",
        devModeOff   = "|cffff0000disabled|r",
    },

    whatsNew = {
        -- Must match the library's own heading, or the panel repeats it.
        section     = "What's New",
        versionInfo = "Version info",
        utilsLabel  = "Lucky's Utils",
    },

    settings = {
        unknownCommand = "Unknown /wbs command. Try: settings, report, autoopen, perf, devopen",
    },

    migration = {
        failed = "Your settings could not be upgraded, so your sets are off for now. Please report this on CurseForge with this code: %s",
    },

    sets = {
        section            = "Sets",
        label              = "Set",
        labelDesc          = "The set these options and the item list apply to. A set is a list of items; give a character as many as you like on the Assignments page.",
        new                = "New",
        newDesc            = "Create an empty set, or a standard set that follows a rule instead of a list, such as every herb in your bags or this week's treatise.",
        newEmpty           = "Empty Set",
        newStandard        = "Standard Sets",
        newReagents        = "Reagents",
        rename             = "Rename",
        renameDesc         = "Give this set a new name. Characters using it keep it.",
        duplicate          = "Duplicate",
        duplicateDesc      = "Copy this set, items and options included, as a starting point for another one.",
        delete             = "Delete",
        deleteDesc         = "Remove this set from every character that uses it.",
        newPrompt          = "Enter new set name:",
        renamePrompt       = "Rename set:",
        deletePrompt       = "Delete set '%s'? Characters using it lose it. This cannot be undone.",
        nameRequired       = "Please enter a set name.",
        nameEmpty          = "Set name cannot be empty.",
        nameTooLong        = "Set name is too long (max 40 characters).",
        nameInvalid        = "Set name contains invalid characters.",
        nameTaken          = "A set named '%s' already exists.",
        usedBy             = "Used by",
        usedByTooltip      = "Opens the Assignments page, where you tick the sets each character uses.",
        usedByNone         = "No characters",
        none               = "Create a set with New to start.",
        type               = "Set Type",
        typeDesc           = "Keep in Bags withdraws each item up to its Keep amount. Deposit All sends every item on the list to your Warband Bank.",
        typeKeep           = "Keep in Bags",
        typeDeposit        = "Deposit All",
        -- No row uses these: Return Extras is on for every set, and the strings
        -- stay for the day it becomes a choice again.
        returnExtras       = "Return Extras",
        returnExtrasDesc   = "Deposits anything above an item's Keep amount into your Warband Bank. When two sets list the same item, extras only go back if every one of them has this on.",
        everyCharacter     = "Every Character",
        everyCharacterDesc = "Gives this set to all your characters, new ones included. Untick it for a character on the Assignments page.",
        currentExpansion   = "Current Expansion Only",
        currentExpansionDesc = "Only deposits reagents from the current expansion. Older materials stay in your bags.",
        migratedGlobal     = "Global (Migrated)",
        migratedCharacter  = "%s (Migrated)",
    },

    standard = {
        herb         = "Herbs",
        leather      = "Leather",
        cloth        = "Cloth",
        metalstone   = "Metal & Stone",
        gems         = "Gems",
        enchanting   = "Enchanting",
        cooking      = "Cooking",
        elemental    = "Elemental",
        crafting     = "Crafting Reagents",
        finishing    = "Finishing Reagents",
        other        = "Other Reagents",
        lumber       = "Lumber",
        treatise     = "Weekly Treatise",
        warbound     = "Warbound Items",
        reagentDesc  = "A standard set: every reagent in the %s category goes from your bags to your Warband Bank. Untick it on the Assignments page for the characters who craft with them.",
        lumberDesc   = "A standard set: all lumber goes from your bags to your Warband Bank.",
        treatiseDesc = "A standard set: keeps one Thalassian Treatise for each of your professions in your bags until you use it this week, withdrawn from your Warband Bank.",
        warboundDesc = "A standard set: the warbound items you tick go from your bags to your Warband Bank as it opens, before your sets restock. Anything a set keeps in your bags is left where it is.",
    },

    items = {
        section           = "Items",
        empty             = "No items in this set. Add one above.",
        noMatches         = "No item matches that filter.",
        filterPlaceholder = "Filter items...",
        unknownItem       = "Item %d",
        itemIdLabel       = "Item ID",
        itemIdTooltip     = "Enter the numeric ID of the item you want to add. You can also drop an item here, or shift-click one while the box is selected.",
        keep              = "Keep",
        keepTooltip       = "How many of this item to keep in your bags.",
        add               = "Add",
        addTooltip        = "Adds the item to the list.",
        remove            = "Remove",
        clear             = "Clear List",
        clearTooltip      = "Removes every item from this set.",
        clearPrompt       = "Clear every item from set '%s'?",
        reserveTag        = "Reserve %d",
    },

    report = {
        title   = "Items your sets keep on this character:",
        empty   = "None of your sets stock this character.",
        line    = "%s (%d): have %d, keep %d",
        extras  = ", extras returned at %d",
        reserve = ", reserve %d",
    },

    characters = {
        section           = "Assignments",
        everyHeading      = "Every Character",
        everyHint         = "These sets run on every character, new ones included.",
        charactersHeading = "Characters",
        noSets            = "No sets",
        noOtherSets       = "No other sets",
        everySuffix       = "(every character)",
        ignore            = "Ignore",
        include           = "Include",
        ignoredCharacters = "Ignored Characters",
        priority          = "Priority",
        priorityDesc      = "Lets this character withdraw below the amounts on the Reserves page.",
    },

    reserves = {
        section      = "Reserves",
        hint         = "The Warband Bank keeps at least this many of each item. Only characters marked Priority on the Assignments page withdraw below it.",
        leave        = "Leave",
        leaveTooltip = "How many of this item the Warband Bank keeps.",
        empty        = "No reserves yet. Add an item above.",
    },

    lowStock = {
        toggle       = "Low Stock Warning",
        tooltip      = "Logging in or entering a rest area opens a small window listing the items from this set your bags are short of. It shows how many the Warband Bank can cover, with the ones you need to buy or craft in red.",
        section      = "Low Stock Warning",
        seconds      = "Show For",
        secondsDesc  = "How long the Low Stock window stays up before fading. Hovering it restarts the count.",
        secondsUnit  = "s",
        stay         = "Keep Open While Resting",
        stayDesc     = "Keeps the Low Stock window up while you are in a city or inn, until you restock or leave. It fades as usual once you head out.",
        tint         = "Red Minimap Button",
        tintDesc     = "Turns the minimap button red while any item on a Low Stock Warning set is short.",
        title        = "Low Stock",
        count        = "%d / %d",
        inBank       = "%d in bank",
        more         = "and %d more",
    },

    restock = {
        tooltip          = "Restock From the Auction House",
        tooltipPrice     = "Click to ask the Auction House for a price.",
        tooltipConfirm   = "Click to buy %s for %s.",
        priced           = "%s costs %s. Click the Restock button again to buy.",
        noPrice          = "The Auction House has no price for %s, skipping it.",
        notEnoughGold    = "Not enough gold for %s.",
        done             = "Nothing left to restock.",
    },

    warbound = {
        armor          = "Warbound Armor",
        armorTooltip   = "Deposits warbound armor from your bags.",
        weapons        = "Warbound Weapons",
        weaponsTooltip = "Deposits warbound weapons from your bags.",
        tokens         = "Warbound Tokens",
        tokensTooltip  = "Deposits warbound tier tokens from your bags.",
        other          = "Other Warbound Items",
        otherTooltip   = "Deposits every other warbound item from your bags, consumables and reagents included.",
        quality        = "Gear Quality",
        qualityTooltip = "Only deposits warbound armor and weapons of this quality or better. Tokens and other items are not affected.",
        qualityAny     = "Any quality",
        qualityOrBetter = "%s or better",
    },

    bank = {
        section       = "Bank",
        sorting       = "Sorting",
        sortAfter     = "Sort Bank After Deposit",
        sortAfterDesc = "Cleans up and sorts your Warband Bank once every deposit has finished.",
    },

    bankQueue = {
        section = "Bank Queue",
    },

    gold = {
        section          = "Gold",
        bracketsSection  = "Level Brackets",
        bracketHint      = "Characters whose level falls within a bracket automatically have their gold balanced when at the Warband Bank. Overrides below always take priority.",
        colMinLevel      = "Min Lvl",
        colMaxLevel      = "Max Lvl",
        colGold          = "Gold (g)",
        addBracket       = "Add Bracket",
        removeBracket    = "Remove",
        overridesSection = "Character Overrides",
        overrideHint     = "Set a specific gold amount for an individual character, overriding any bracket. Leave blank or set 0 to remove.",
        colCharacter     = "Character",
        addOverride      = "Add Override",
        removeOverride   = "Remove",
        createBracket    = "Create / Adjust Bracket",
        createOverride   = "Create / Adjust Override",
        noBrackets       = "No brackets defined. Add one below.",
        noOverrides      = "No character overrides set. Add one below.",
        selectCharacter  = "Select character...",
        invalidBracket   = "Enter valid Min (1 or more), Max (Min or more), Gold (above 0).",
        invalidOverride  = "Select a character and enter a gold amount above 0.",
        deposited        = "Deposited %dg %ds %dc to Warband Bank.",
        withdrew         = "Withdrew %dg %ds %dc from Warband Bank.",
    },

    commands = {
        depositUsage      = "Usage: /wbdeposit <itemID>",
        depositExample    = "Example: /wbdeposit 6948",
        bankUnavailable   = "Warband bank is not available. You must be at a warband bank to use this command.",
        itemIdFallback    = "Item ID: %d",
        depositSuccess    = "Deposited 1x %s into warband bank.",
        withdrawInvalid   = "Please provide a valid item ID or item link.",
        withdrawUsage     = "|cffccccccUsage:|r /wbwithdraw <itemID> or /wbwithdraw [item link]",
        invalidItemId     = "Invalid item ID: %s",
        helpTitle         = "|cff7fd5ff[Warband Stockist] Available Commands:|r",
        helpDeposit       = "|cff00ff00/wbdeposit <itemID>|r - Deposit 1 of the specified item into warband bank",
        helpDepositAlias  = "|cff00ff00/warbanddeposit <itemID>|r - Same as above",
        helpWithdraw      = "|cff00ff00/wbwithdraw <itemID>|r - Withdraw 1 of the specified item from warband bank",
        helpWithdrawAlias = "|cff00ff00/warbandwithdraw <itemID>|r - Same as above",
        helpHelp          = "|cff00ff00/wbhelp|r - Show this help message",
        helpNote          = "|cffccccccNote:|r You must be at a warband bank to use these commands.",
        loaded            = "Deposit commands loaded. Type /wbhelp for usage.",
    },
})
